[2024-10-29 02:39:36,769] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.store_data_json scheduled__2024-10-29T02:37:25.442820+00:00 [queued]>
[2024-10-29 02:39:36,785] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.store_data_json scheduled__2024-10-29T02:37:25.442820+00:00 [queued]>
[2024-10-29 02:39:36,786] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 02:39:36,787] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-29 02:39:36,787] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 02:39:36,810] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_data_json> on 2024-10-29 02:37:25.442820+00:00
[2024-10-29 02:39:36,818] {standard_task_runner.py:52} INFO - Started process 473 to run task
[2024-10-29 02:39:36,821] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'store_data_json', 'scheduled__2024-10-29T02:37:25.442820+00:00', '--job-id', '552', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmp835wonco', '--error-file', '/tmp/tmpgzs1um1d']
[2024-10-29 02:39:36,822] {standard_task_runner.py:80} INFO - Job 552: Subtask store_data_json
[2024-10-29 02:39:36,897] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.store_data_json scheduled__2024-10-29T02:37:25.442820+00:00 [running]> on host 31266dfed982
[2024-10-29 02:39:37,003] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=store_data_json
AIRFLOW_CTX_EXECUTION_DATE=2024-10-29T02:37:25.442820+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-29T02:37:25.442820+00:00
[2024-10-29 02:39:37,060] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 81, in _store_data_json
    json_path = Variable.get('parking_data_json_path')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 138, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable parking_data_json_path does not exist'
[2024-10-29 02:39:37,078] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=store_data_json, execution_date=20241029T023725, start_date=20241029T023936, end_date=20241029T023937
[2024-10-29 02:39:37,097] {standard_task_runner.py:97} ERROR - Failed to execute job 552 for task store_data_json ('Variable parking_data_json_path does not exist'; 473)
[2024-10-29 02:39:37,114] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 02:39:37,185] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
