[2022-12-27 23:25:19,166] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.load_data manual__2022-12-27T23:25:12.790616+00:00 [queued]>
[2022-12-27 23:25:19,174] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.load_data manual__2022-12-27T23:25:12.790616+00:00 [queued]>
[2022-12-27 23:25:19,175] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 23:25:19,176] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-27 23:25:19,177] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 23:25:19,187] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_data> on 2022-12-27 23:25:12.790616+00:00
[2022-12-27 23:25:19,191] {standard_task_runner.py:52} INFO - Started process 13979 to run task
[2022-12-27 23:25:19,195] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'load_data', 'manual__2022-12-27T23:25:12.790616+00:00', '--job-id', '727', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmpsne2zy0a', '--error-file', '/tmp/tmpbuat3shn']
[2022-12-27 23:25:19,197] {standard_task_runner.py:80} INFO - Job 727: Subtask load_data
[2022-12-27 23:25:19,248] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.load_data manual__2022-12-27T23:25:12.790616+00:00 [running]> on host 8fbeee8d3d5a
[2022-12-27 23:25:19,309] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T23:25:12.790616+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T23:25:12.790616+00:00
[2022-12-27 23:25:19,319] {postgres.py:127} INFO - Running copy expert: COPY parking_data FROM stdin WITH DELIMITER as ',', filename: ./tmp/processed_parking_data_00.csv
[2022-12-27 23:25:19,328] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-12-27 23:25:19,335] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 72, in _load_parking_data
    filename=filename
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "2015-12-31T17:40:58.000Z"
CONTEXT:  COPY parking_data, line 1, column parkingtransactionkey: "2015-12-31T17:40:58.000Z"

[2022-12-27 23:25:19,347] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=load_data, execution_date=20221227T232512, start_date=20221227T232519, end_date=20221227T232519
[2022-12-27 23:25:19,355] {standard_task_runner.py:97} ERROR - Failed to execute job 727 for task load_data (invalid input syntax for type integer: "2015-12-31T17:40:58.000Z"
CONTEXT:  COPY parking_data, line 1, column parkingtransactionkey: "2015-12-31T17:40:58.000Z"
; 13979)
[2022-12-27 23:25:19,368] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-27 23:25:19,396] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
