[2022-12-27 20:53:19,915] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T20:46:15.102450+00:00 [queued]>
[2022-12-27 20:53:19,922] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T20:46:15.102450+00:00 [queued]>
[2022-12-27 20:53:19,922] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 20:53:19,923] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-12-27 20:53:19,923] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 20:53:19,933] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_data> on 2022-12-27 20:46:15.102450+00:00
[2022-12-27 20:53:19,937] {standard_task_runner.py:52} INFO - Started process 7778 to run task
[2022-12-27 20:53:19,942] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'transform_data', 'scheduled__2022-12-27T20:46:15.102450+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmp9l3ts336', '--error-file', '/tmp/tmpm58s9pu6']
[2022-12-27 20:53:19,944] {standard_task_runner.py:80} INFO - Job 307: Subtask transform_data
[2022-12-27 20:53:20,000] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T20:46:15.102450+00:00 [running]> on host 8fbeee8d3d5a
[2022-12-27 20:53:20,064] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T20:46:15.102450+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-27T20:46:15.102450+00:00
[2022-12-27 20:53:20,078] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 37, in _transform_parking_data
    df = pd.json_normalize(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_normalize.py", line 423, in _json_normalize
    raise NotImplementedError
NotImplementedError
[2022-12-27 20:53:20,091] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parking_pipeline, task_id=transform_data, execution_date=20221227T204615, start_date=20221227T205319, end_date=20221227T205320
[2022-12-27 20:53:20,098] {standard_task_runner.py:97} ERROR - Failed to execute job 307 for task transform_data (; 7778)
[2022-12-27 20:53:20,114] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-27 20:53:20,144] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
