[2022-12-27 23:28:23,482] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.load_data manual__2022-12-27T23:28:17.243669+00:00 [queued]>
[2022-12-27 23:28:23,489] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.load_data manual__2022-12-27T23:28:17.243669+00:00 [queued]>
[2022-12-27 23:28:23,489] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 23:28:23,490] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-27 23:28:23,490] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 23:28:23,499] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_data> on 2022-12-27 23:28:17.243669+00:00
[2022-12-27 23:28:23,504] {standard_task_runner.py:52} INFO - Started process 14197 to run task
[2022-12-27 23:28:23,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'load_data', 'manual__2022-12-27T23:28:17.243669+00:00', '--job-id', '752', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmph14nmll6', '--error-file', '/tmp/tmpykobv_ie']
[2022-12-27 23:28:23,509] {standard_task_runner.py:80} INFO - Job 752: Subtask load_data
[2022-12-27 23:28:23,562] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.load_data manual__2022-12-27T23:28:17.243669+00:00 [running]> on host 8fbeee8d3d5a
[2022-12-27 23:28:23,631] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T23:28:17.243669+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T23:28:17.243669+00:00
[2022-12-27 23:28:23,641] {postgres.py:127} INFO - Running copy expert: COPY parking_data FROM stdin WITH DELIMITER as ',', filename: ./tmp/processed_parking_data_00.csv
[2022-12-27 23:28:23,651] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-12-27 23:28:23,659] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 72, in _load_parking_data
    filename=filename
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: ""
CONTEXT:  COPY parking_data, line 32, column dollarperhourrate: ""

[2022-12-27 23:28:23,672] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=load_data, execution_date=20221227T232817, start_date=20221227T232823, end_date=20221227T232823
[2022-12-27 23:28:23,681] {standard_task_runner.py:97} ERROR - Failed to execute job 752 for task load_data (invalid input syntax for type double precision: ""
CONTEXT:  COPY parking_data, line 32, column dollarperhourrate: ""
; 14197)
[2022-12-27 23:28:23,720] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-27 23:28:23,757] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
